### PR TITLE
Initial cd setup

### PR DESCRIPTION
**Pull request by jzc1828**
### Initial cd setup
- [x] Add CD using GitHub Actions (CD takes around **9 mins** to complete)
**Update**: did some optimization to reduce build time to **~4 mins** for new build and **~2 mins** for an updated build 😄
image
image
 
- [x] Add caching to CI and CD workflows (after some testing, CI with caching is **20s** faster than without caching lol)
image

### CODE REVIEW

**Comment by jzc1828** [comment]
> Looks good as long as you tested it. I also think we should add the yarn.lock file to the repo and change the .gitignore to only ignore package-lock.json.
> 
> https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
> 
> This is so that everyone on the team and production server all have the same dependencies versions.

sure

**Comment by jzc1828** [comment]
> Looks fine. Surprised that it takes 9 minutes though. Does it break down which step takes the longest?

@yummyblabla https://github.com/GamblingKings/GamblingKingsBackend/runs/985699075?check_suite_focus=true

**Comment by yummyblabla** [comment]
Could be faster the second time when the CloudFormation stack is already there

**Comment by jzc1828** [comment]
> Could be faster the second time when the CloudFormation stack is already there

I deployed before, so it was updating the same stack

**Comment by jzc1828** [comment]
deployment is pretty fast, its webpack (or serverless-webpack) that slows everything down (by almost 90% lol).

**Pull request merged**
